[common]
lib_deps = https://github.com/joltwallet/esp_littlefs.git
           git@gitlab.com:nicholaszww/osal.git


[env:m5stack-cores3]
platform = espressif32
board = m5stack-cores3
framework = espidf
monitor_speed = 115200
; extra_scripts = post:genFirmware.py
board_build.partitions = esp32s3_16M.csv
board_build.filesystem = littlefs

build_flags =
    -std=c++17
    -DOSAL_OS=freertos
    -DBUILD_DOCS=OFF
    -DOSAL_BUILD_TESTS=OFF
    -DOSAL_ENABLE_COVERAGE=OFF
    -DFIPC_BUILD_TESTS=OFF
    -DFIPC_ENABLE_COVERAGE=OFF

lib_deps =
    ${common.lib_deps}
    m5stack/M5Unified@^0.2.13
    m5stack/M5GFX@^0.2.19

lib_ignore =
    osal
