[common]
lib_deps = https://github.com/joltwallet/esp_littlefs.git


[env:m5stack-cores3]
platform = espressif32
board = m5stack-cores3
framework = espidf
monitor_speed = 115200
board_build.partitions = esp32s3_16M.csv
board_build.filesystem = littlefs

build_flags =
    -std=gnu++17

lib_deps = ${common.lib_deps}